export const jobsData = [
  {
    id: 1,
    title: 'Junior Web Developer',
    company: 'Tech Startup',
    salary: '₹3,00,000 - ₹5,00,000',
    location: 'Remote',
    requiredEducation: 'bachelor',
    requiredSkills: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
    minExperience: 0,
    description: 'Looking for a junior web developer with knowledge of modern web technologies.',
  },
  {
    id: 2,
    title: 'Full Stack Developer',
    company: 'E-commerce Company',
    salary: '₹6,00,000 - ₹9,00,000',
    location: 'Bangalore',
    requiredEducation: 'bachelor',
    requiredSkills: ['JavaScript', 'React', 'Node.js', 'PostgreSQL', 'AWS'],
    minExperience: 2,
    description: 'Experienced full stack developer for e-commerce platform development.',
  },
  {
    id: 3,
    title: 'Data Analyst',
    company: 'Finance Corp',
    salary: '₹4,00,000 - ₹6,00,000',
    location: 'Mumbai',
    requiredEducation: 'bachelor',
    requiredSkills: ['Excel', 'SQL', 'Python', 'Tableau', 'Statistics'],
    minExperience: 1,
    description: 'Data analyst to work on financial data and create insights.',
  },
  {
    id: 4,
    title: 'UX/UI Designer',
    company: 'Design Agency',
    salary: '₹3,50,000 - ₹5,50,000',
    location: 'Delhi',
    requiredEducation: '12th',
    requiredSkills: ['Figma', 'Adobe XD', 'UI Design', 'User Research', 'Prototyping'],
    minExperience: 0,
    description: 'Creative UX/UI designer to create amazing user interfaces.',
  },
  {
    id: 5,
    title: 'Digital Marketing Executive',
    company: 'Marketing Agency',
    salary: '₹2,50,000 - ₹4,00,000',
    location: 'Hyderabad',
    requiredEducation: '12th',
    requiredSkills: ['SEO', 'Social Media', 'Content Writing', 'Google Analytics'],
    minExperience: 0,
    description: 'Marketing executive to manage digital campaigns and content.',
  },
  {
    id: 6,
    title: 'Python Developer',
    company: 'AI Company',
    salary: '₹5,00,000 - ₹8,00,000',
    location: 'Bangalore',
    requiredEducation: 'bachelor',
    requiredSkills: ['Python', 'Machine Learning', 'TensorFlow', 'Data Science'],
    minExperience: 1,
    description: 'Python developer for AI and machine learning projects.',
  },
];

export const skillsData = [
  {
    id: 1,
    name: 'JavaScript',
    category: 'Programming',
    difficulty: 'Beginner',
    learningTime: 80,
    relatedJobs: [1, 2],
  },
  {
    id: 2,
    name: 'React',
    category: 'Web Development',
    difficulty: 'Intermediate',
    learningTime: 60,
    relatedJobs: [1, 2],
  },
  {
    id: 3,
    name: 'Node.js',
    category: 'Backend',
    difficulty: 'Intermediate',
    learningTime: 50,
    relatedJobs: [2],
  },
  {
    id: 4,
    name: 'Python',
    category: 'Programming',
    difficulty: 'Beginner',
    learningTime: 70,
    relatedJobs: [6],
  },
  {
    id: 5,
    name: 'Machine Learning',
    category: 'AI/ML',
    difficulty: 'Advanced',
    learningTime: 120,
    relatedJobs: [6],
  },
  {
    id: 6,
    name: 'UI/UX Design',
    category: 'Design',
    difficulty: 'Intermediate',
    learningTime: 90,
    relatedJobs: [4],
  },
];

export const coursesData = [
  {
    id: 1,
    title: 'JavaScript Basics',
    provider: 'internal',
    skillTaught: 'JavaScript',
    duration: 40,
    level: 'Beginner',
    internalContent: true,
    price: 0,
  },
  {
    id: 2,
    title: 'React for Beginners',
    provider: 'internal',
    skillTaught: 'React',
    duration: 50,
    level: 'Beginner',
    internalContent: true,
    price: 0,
  },
  {
    id: 3,
    title: 'Node.js & Express',
    provider: 'internal',
    skillTaught: 'Node.js',
    duration: 40,
    level: 'Intermediate',
    internalContent: true,
    price: 0,
  },
  {
    id: 4,
    title: 'Python for Data Science',
    provider: 'external',
    skillTaught: 'Python',
    duration: 60,
    level: 'Intermediate',
    internalContent: false,
    price: 2999,
    link: 'https://www.udemy.com/course/python-for-data-science/',
  },
  {
    id: 5,
    title: 'Complete Web Design',
    provider: 'external',
    skillTaught: 'UI/UX Design',
    duration: 80,
    level: 'Beginner',
    internalContent: false,
    price: 3999,
    link: 'https://www.udemy.com/course/web-design/',
  },
];
